### ISSUE TITLE
Warn if auto-merge gets activated, but the PR isn't approved yet

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/dlang-bot#103] opened 2017-06-27 20:12 UTC
Only relevant for repos which require approval, e.g. {phobos, druntime, dlang.org}. Currently, dmd does not.

**Comment by MartinNowak** [comment] 2018-01-15 17:05
Closed as duplicate of #74

**Closed by MartinNowak** 2018-01-15 17:05 UTC
